use std::sync::Mutex;
use std::sync::Arc;
use std::sync::Weak;
use super::grid::*;
use super::node::*;
use super::edge::*;
use super::graph::*;
pub type GridRef = Arc<Mutex<Grid>>;
pub type NodeRef = Arc<Mutex<Node>>;
pub type EdgeRef = Arc<Mutex<Edge>>;
pub type GraphRef = Arc<Mutex<Graph>>;
pub type WeakNodeRef = Weak<Mutex<Node>>;
pub type WeakEdgeRef = Weak<Mutex<Edge>>;