use std::cell::RefCell;
use std::rc::Rc;
use std::rc::Weak;
use super::grid::*;
use super::node::*;
use super::edge::*;
use super::graph::*;
pub type GridRef = Rc<RefCell<Grid>>;
pub type NodeRef = Rc<RefCell<Node>>;
pub type EdgeRef = Rc<RefCell<Edge>>;
pub type GraphRef = Rc<RefCell<Graph>>;
pub type WeakNodeRef = Weak<RefCell<Node>>;
pub type WeakEdgeRef = Weak<RefCell<Edge>>;